import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import useSWR from 'swr'
import {Line} from 'react-chartjs-2'
import Link from 'next/link'

const fetcher = url => fetch(url).then(res => res.json());

export default function Home({orders}) {
  console.log(orders);
  return (
    <div className={styles.container}>
      <Head>
        <title>Vaccinations App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Vaccinations App!
        </h1>

        <OrderCount />

        <Link href="/orders/statistics">
          <a>Order statistics</a>
        </Link>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

function VaccinationCount() {
  const { data, error } = useSWR(
    "api/vaccinations/count",
    fetcher
  );

  if (!data) return "Loading...";

  return (
    <p className={styles.description}>
      Vaccinations in this application: {data}
    </p>
  )
}

function OrderCount() {
  const { data, error } = useSWR(
    "api/orders/count",
    fetcher
  );

  if (!data) return "Loading...";

  return (
    <p className={styles.description}>
      Orders in this application: {data}
    </p>
  )
}

export const getStaticProps = async () => {
  const { data, error } = useSWR(
    "api/orders",
    fetcher
  );

  const orders = await data.json();

  return {
    props: {
      orders
    }
  }
}